version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn elite.wsgi:application --bind 0.0.0.0:8000
    container_name: elite_web_1
    volumes:
      - .:/home/app
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/media
    ports:
      - 8080:8000
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
      - redis
    networks:
      - elite_network

 
  db:
    image: postgis/postgis:15-3.3
    container_name: elite_db_1
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    expose:
      - "5432"
    networks:
        - elite_network

  redis:
    image: redis:latest
    container_name: elite_redis_1
    ports:
      - "6380:6379"
    restart: always
    networks:   
      - elite_network
    volumes:
      - redis_data:/data

  nginx:
    image: nginx
    build: ./nginx
    env_file:
      - ./.env
    ports:
      - "9000:8080"
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/media
    depends_on:
      - web
    restart: always
    networks:
      - elite_network


networks:
  elite_network:
    driver: bridge

volumes:
  postgres_data:
  media_volume:
  static_volume:
  redis_data: